[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "metagene"
version = "0.0.0.dev3"
description = "Metagene Profiling Analysis and Visualization"
authors = ["Ye Chang <yech1990@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/y9c/metagene"
documentation = "https://cf.readthedocs.io/"
keywords = ["DNA", "RNA", "metagene", "biology"]

[tool.poetry.dependencies]
python = "^3.8"
Click = "^7.0.0"
matplotlib = "^3.0.0"
pyranges = "^0.0.117"
ray = "^1.13.0"

[tool.poetry.dev-dependencies]
twine = "^3.1.1"

[tool.poetry.scripts]
metagene = "metagene.cli:cli"
