[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "metagene"
version = "0.0.0.dev47"
description = "Metagene Profiling Analysis and Visualization"
authors = ["Ye Chang <yech1990@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/y9c/metagene"
documentation = "https://cf.readthedocs.io/"
keywords = ["DNA", "RNA", "metagene", "biology"]

[tool.poetry.dependencies]
python = "^3.8"
Click = "^8.0.0"
matplotlib = "^3.0.0"
pyranges = "^0.0.117"
pandas = "^2.0.2"
ray = "^2.6.3"
pyarrow = "^13.0.0"
polars="< 0.16.14"
gtfparse = "^2.0.1"
rich = "^13.5.2"
rich-click = "^1.6.1"
asciichartpy = "^1.5.25"

[tool.poetry.dev-dependencies]
twine = "^3.1.1"

[tool.poetry.scripts]
metagene = "metagene.cli:cli"

[tool.black]
line-length = 79
